### ISSUE TITLE
yt tests failing on Travis

### ISSUE THREAD

**Issue by ketch** [ketch/griddle#3]
No idea why.

```
======================================================================
ERROR: griddle.test.test_animation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/ketch/griddle/test.py", line 52, in test_animation
    animation = griddle.animate(plotitems)
  File "/home/travis/build/ketch/griddle/plot.py", line 169, in animate
    import yt.visualization
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/yt/__init__.py", line 81, in <module>
    from yt.funcs import \
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/yt/funcs.py", line 28, in <module>
    import yt.extern.progressbar as pb
AttributeError: 'module' object has no attribute 'extern'
```

**Comment by ketch** [comment]
For now I have made it so these tests are skipped if the import fails.

**Comment by ketch** [comment]
The failure above was due to me not installing all the yt dependencies.  Now that is fixed, but I am seeing the following:

```
======================================================================
FAIL: griddle.tests.plot_tests.test_amr_plotting.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/matplotlib/testing/decorators.py", line 51, in failer
    result = f(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/matplotlib/testing/decorators.py", line 196, in do_test
    '(RMS %(rms).3f)'%err)
ImageComparisonFailure: images not close: /home/travis/build/ketch/griddle/result_images/plot_tests/amr_pdf.png vs. /home/travis/build/ketch/griddle/result_images/plot_tests/amr-expected_pdf.png (RMS 40.859)
```

That's very strange, since the test passes if we don't install Travis.

**Comment by ketch** [comment]
Update, January 2018: It looks like now a yt test is failing due to not having h5py installed correctly.
